<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Poll
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.net/license/
 * @version    $Id: changelog.php 9689 2012-04-19 00:22:35Z richard $
 * @author     John
 */
return array(
  '4.2.3' => array(
    '/application/languages/en/poll.csv' => 'Rewrite Profile viewing and Profile Commenting Options Descriptions',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.2.0' => array(
    'externals/scripts/core.js' => 'Added namespace for Wibiya compatibility',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.1.8' => array(
    'controllers/IndexController.php' => 'Added pages to the layout editor',
    'controllers/PollController.php' => 'Added pages to the layout editor',
    'externals/.htaccess' => 'Updated with far-future expires headers for static resources',
    'externals/styles/main.css' => 'Style tweaks for layout editor',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added pages to the layout editor',
    'settings/install.php' => 'Added pages to the layout editor',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_poll.tpl' => 'Added static base URL for CDN support',
    'views/scripts/admin-manage/index.tpl' => 'Added static base URL for CDN support',
    'views/scripts/index/browse.tpl' => 'Added pages to the layout editor; Added static base URL for CDN support',
    'views/scripts/index/create.tpl' => 'Compatibility for AJAX page loader',
    'views/scripts/index/manage.tpl' => 'Added static base URL for CDN support',
    'views/scripts/poll/view.tpl' => 'Added pages to the layout editor; Added static base URL for CDN support',
    'widgets/browse-menu-quick/Controller.php' => 'Added',
    'widgets/browse-menu-quick/index.tpl' => 'Added',
    'widgets/browse-menu/Controller.php' => 'Added',
    'widgets/browse-menu/index.tpl' => 'Added',
    'widgets/browse-search/Controller.php' => 'Added',
    'widgets/browse-search/index.tpl' => 'Added',
    'widgets/profile-polls/Controller.php' => 'Fixed issue where title would not be displayed when placed outside a tab container widget',
  ),
  '4.1.7' => array(
    'Api/Core.php' => 'Merging methods from api to dbtables',
    'controllers/AdminManageController.php' => 'Merging methods from api to dbtables; minor optimizations',
    'controllers/AdminSettingsController.php' => 'Merging methods from api to dbtables; minor optimizations',
    'controllers/IndexController.php' => 'Merging methods from api to dbtables; minor optimizations',
    'controllers/PollController.php' => 'Merging methods from api to dbtables; minor optimizations',
    'Model/DbTable/Polls.php' => 'Merging methods from api to dbtables; minor optimizations',
    'Model/Poll.php' => 'Merging methods from api to dbtables; minor optimizations',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'widgets/profile-polls/Controller.php' => 'Merging methods from api to dbtables; minor optimizations',
  ),
  '4.1.6' => array(
    'controllers/IndexController.php' => 'Added the ability to open and close polls',
    'controllers/PollController.php' => 'Added',
    'externals/images/close.png' => 'Added',
    'externals/images/unclose.png' => 'Added',
    'externals/scripts/core.js' => 'Added the ability to open and close polls',
    'externals/styles/main.css' => 'Added styles',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.4-4.1.6.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_poll.tpl' => 'Added the ability to open and close polls',
    'views/scripts/index/browse.tpl' => 'Added the ability to open and close polls',
    'views/scripts/index/delete.tpl' => 'Moved',
    'views/scripts/index/edit.tpl' => 'Moved',
    'views/scripts/index/manage.tpl' => 'Added the ability to open and close polls',
    'views/scripts/index/view.tpl' => 'Moved',
    'views/scripts/poll/*' => 'Added',
  ),
  '4.1.4' => array(
    'controllers/AdminSettingsController.php' => 'Fixed issues with saving global settings',
    'controllers/IndexController.php' => 'Fixed issues with saving global settings',
    'externals/styles/main.css' => 'Added svn:keywords Id',
    'externals/styles/mobile.css' => 'Added',
    'Form/Admin/Global.php' => 'Removed',
    'Form/Admin/Settings/Global.php' => 'Added',
    'Model/Poll.php' => 'Fixed issues with saving global settings',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.3-4.1.4.sql' => 'Added',
    'settings/my.sql' => 'Incremented version; Inserts menu item for mobile',
    'widgets/home-poll/Controller.php' => 'Fixed issues with saving global settings',
  ),
  '4.1.3' => array(
    'Model/Poll.php' => 'Fixed issue that caused incorrect counts when changing a vote',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.1.2' => array(
    'Api/Core.php' => 'Renamed views column to view_count',
    'controllers/IndexController.php' => 'Renamed views column to view_count',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.1-4.1.2.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_poll.tpl' => 'Renamed views column to view_count',
    'views/scripts/admin-manage/index.tpl' => 'Renamed views column to view_count',
    'views/scripts/index/browse.tpl' => 'Renamed views column to view_count',
    'views/scripts/index/manage.tpl' => 'Renamed views column to view_count',
    'widgets/home-poll/index.tpl' => 'Renamed views column to view_count',
    'widgets/list-popular-polls/Controller.php' => 'Added',
    'widgets/list-popular-polls/index.tpl' => 'Added',
    'widgets/list-recent-polls/Controller.php' => 'Added',
    'widgets/list-recent-polls/index.tpl' => 'Added',
  ),
  '4.1.1' => array(
    'externals/.htaccess' => 'Added keywords; removed deprecated code',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.1.0' => array(
    '/application/languages/en/poll.csv' => 'Fixed phrases with stray double-quotes',
    'Api/Core.php' => 'Added filtering options',
    'controllers/AdminManageController.php' => 'Fixed deletion issues',
    'controllers/AdminSettingsController.php' => 'Added notice on form save',
    'controllers/IndexController.php' => 'Fixed issue with poll searching',
    'Form/Admin/Global.php' => 'Fixed issue with disabling privacy options',
    'Form/Create.php' => 'Fixed issue with disabling privacy options',
    'Form/Delete.php' => 'Added',
    'Plugin/Job/Maintenance/RebuildPrivacy.php' => 'Added',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Removed',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added pagination/item count limits to widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Backwards compatibility fix for tasks modifications',
    'settings/my-upgrade-4.0.5-4.1.0.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/deleteselected.tpl' => 'Removed',
    'views/scripts/admin-manage/index.tpl' => 'Fixed deletion issues',
    'views/scripts/index/delete.tpl' => 'UI improvements',
    'views/scripts/index/manage.tpl' => 'UI improvements',
    'widgets/profile-polls/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-polls/index.tpl' => 'Added pagination/item count limit',
  ),
  '4.0.5' => array(
    'Api/Core.php' => 'Added new filtering options; removing deprecated code',
    'controllers/AdminManageController.php' => 'Added admin suggest action for widget edit form',
    'controllers/IndexController.php' => 'Various auth, paginatiom, filtering improvements; added menus to menu editor',
    'externals/images/nophoto_poll_thumb_icon.png' => 'Added',
    'externals/scripts/core.js' => 'Added',
    'externals/styles/admin/main.css' => 'Added',
    'externals/styles/main.css' => 'Added styles for new widget and feed rich content',
    'Form/Admin/Settings/Level.php' => 'Added registered privacy type',
    'Form/Admin/Widget/HomePoll.php' => 'Added',
    'Form/Create.php' => 'Added registered privacy type',
    'Form/Index/Search.php' => 'Removed',
    'Form/Index/Vote.php' => 'Removed',
    'Form/Search.php' => 'Added',
    'Model/Poll.php' => 'Added search indexing of poll option labels; added poll display/voting in the feed; performance improvements; removed deprecated code',
    'Plugin/Core.php' => 'Removed deprecated code',
    'Plugin/Menus.php' => 'Added',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added idle support',
    'settings/changelog.php' => 'Added',
    'settings/content.php' => 'Added widget',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.4-4.0.5.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_poll.tpl' => 'Added',
    'views/scripts/admin-manage/index.tpl' => 'Added title truncation',
    'views/scripts/index/browse.tpl' => 'Improved pagination and filtering; added menus to menu editor',
    'views/scripts/index/manage.tpl' => 'Improved pagination and filtering; added menus to menu editor',
    'views/scripts/index/view.tpl' => 'Moved a lot of code to core.js and _poll.tpl',
    'widgets/home-poll/admin.tpl' => 'Added',
    'widgets/home-poll/Controller.php' => 'Added',
    'widgets/home-poll/index.tpl' => 'Added',
    'widgets/profile-polls/index.tpl' => 'Removed deprecated route',
    '/application/languages/en/poll.csv' => 'Added missing phrases',
  ),
  '4.0.4' => array(
    'externals/styles/main.css' => 'Improved RTL support',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added to fix privacy issues in the feed',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/manage.tpl' => 'Added missing translation',
    '/application/languages/en/poll.csv' => 'Added missing phrases',
  ),
  '4.0.3' => array(
    'controllers/IndexController.php' => 'Fixed activity privacy bug',
    'Form/Create.php' => 'Added',
    'Form/Edit.php' => 'Added',
    'Form/Index/Create.php' => 'Moved',
    'Form/Index/Edit.php' => 'Moved',
    'Model/Poll.php' => 'Fixed search indexing bug',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/index.tpl' => 'Added correct locale date format',
    'views/scripts/index/create.tpl' => 'Added re-population of options on failed validation',
    '/application/languages/en/poll.csv' => 'Added phrases',
  ),
  '4.0.2' => array(
    'controllers/AdminSettingsController.php' => 'Various level settings fixes and enhancements',
    'Form/Admin/Level.php' => 'Moved',
    'Form/Admin/Settings/Level.php' => 'Various level settings fixes and enhancements',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Added',
    'settings/my.sql' => 'Various level settings fixes and enhancements',
  ),
  '4.0.1' => array(
    'controllers/AdminSettingsController.php' => 'Fixed problem in level select',
    'controllers/IndexController.php' => 'Fixed public permissions',
    'Plugin/Core.php' => 'Query optimization',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.0-4.0.1.sql' => 'Added',
    'settings/my.sql' => 'Added missing search, view_count, comment_count columns to the engine4_poll_polls table',
  ),
) ?>