<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Album
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.com/license/
 * @version    $Id: changelog.php 9747 2012-07-26 02:08:08Z john $
 * @author     Jung
 */
return array(
  '4.2.5' => array(
    '/application/languages/en/album.csv' => 'Fixed typo in admin panel',
    'Form/Admin/Settings/Level.php' => 'Fixed typo in admin panel',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.7-4.2.5.sql' => 'Adds All Categories to album search',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/index.tpl' => 'Add support links',
  ),
  '4.2.3' => array(
    '/application/languages/en/album.csv' => 'Rewrite Profile viewing and Profile Commenting Options Descriptions',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.2.0' => array(
    'externals/scripts/composer_photo.js' => 'Added namespace for Wibiya compatibility',
    'externals/scripts/core.js' => 'Added namespace for Wibiya compatibility',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.1.8p1' => array(
    'controllers/IndexController.php' => 'Fixed error when category is empty',
    'externals/scripts/composer_photo.js' => 'Added cross domain policy file for CDN support',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.1.8' => array(
    'controllers/AdminSettingsController.php' => 'Fixed typo in variable name',
    'controllers/AlbumController.php' => 'Added pages to the layout editor; added ability to move photos between albums; fixed issue with ordering photos',
    'controllers/IndexController.php' => 'Added pages to the layout editor; fixed issue with ordering photos',
    'controllers/PhotoController.php' => 'Added pages to the layout editor',
    'externals/.htaccess' => 'Updated with far-future expires headers for static resources',
    'externals/styles/main.css' => 'Style tweaks for layout editor',
    'Form/Album.php' => 'Fixed issue where photo could be placed in the incorrect album',
    'Form/Album/EditPhoto.php' => 'Added ability to move photos between albums',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added pages to the layout editor',
    'settings/install.php' => 'Added pages to the layout editor',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_composePhoto.tpl' => 'Added static base URL for CDN support',
    'views/scripts/admin-settings/categories.tpl' => 'Added static base URL for CDN support',
    'views/scripts/album/view.tpl' => 'Added pages to the layout editor',
    'views/scripts/index/browse.tpl' => 'Added pages to the layout editor',
    'views/scripts/photo/view.tpl' => 'Added static base URL for CDN support; compatibility for AJAX page loader',
    'widgets/browse-menu-quick/Controller.php' => 'Added',
    'widgets/browse-menu-quick/index.tpl' => 'Added',
    'widgets/browse-menu/Controller.php' => 'Added',
    'widgets/browse-menu/index.tpl' => 'Added',
    'widgets/browse-search/Controller.php' => 'Added',
    'widgets/browse-search/index.tpl' => 'Added',
    'widgets/profile-albums/Controller.php' => 'Fixed issue where title would not be displayed when placed outside a tab container widget',
  ),
  '4.1.7p1' => array(
    'Album/Form/Album.php' => 'Fixed issue with array_merge that could cause photos to be put into the incorrect album',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.1.7' => array(
    'Api/Core.php' => 'Merging methods from api to dbtables',
    'controllers/AdminManageController.php' => 'Merging methods from api to dbtables',
    'controllers/AdminSettingsController.php' => 'Merging methods from api to dbtables',
    'controllers/AlbumController.php' => 'Merging methods from api to dbtables',
    'controllers/PhotoController.php' => 'Merging methods from api to dbtables',
    'Form/Album.php' => 'Minor optimizations',
    'Form/Album/Edit.php' => 'Minor optimizations',
    'Form/Search.php' => 'Minor optimizations',
    'Model/Album.php' => 'Minor optimizations',
    'Model/Category.php' => 'Minor optimizations',
    'Model/DbTable/Albums.php' => 'Minor optimizations',
    'Model/DbTable/Categories.php' => 'Minor optimizations',
    'Model/DbTable/Photos.php' => 'Minor optimizations',
    'Model/Photo.php' => 'Minor optimizations',
    'Plugin/Core.php' => 'Minor optimizations',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.5-4.1.7.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/photo/view.tpl' => 'Minor optimizations',
    'widgets/list-popular-photos/Controller.php' => 'Minor optimizations',
    'widgets/list-recent-photos/Controller.php' => 'Minor optimizations',
    'widgets/profile-albums/Controller.php' => 'Minor optimizations',
  ),
  '4.1.5' => array(
    'controllers/AlbumController.php' => 'Remove form elements when not necessary by admin configuration',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.1.4' => array(
    'controllers/IndexController.php' => 'Fixed the issue of some servers not filtering the search correctly',
    'controllers/PhotoController.php' => 'Added rotate and flip options',
    'externals/images/flip_horizontal.png' => 'Added',
    'externals/images/flip_vertical.png' => 'Added',
    'externals/images/rotate_ccw.png' => 'Added',
    'externals/images/rotate_cw.png' => 'Added',
    'externals/scripts/core.js' => 'Added functions for rotate and flip options',
    'externals/styles/main.css' => 'Added styles for rotate and flip options',
    'externals/styles/mobile.css' => 'Added',
    'Form/Album.php' => 'Fixed issue of album variable missing notice',
    'Model/DbTable/Albums.php' => 'Added blog as a special album',
    'Model/Photo.php' => 'Different',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.3-4.1.4.sql' => 'Added',
    'settings/my.sql' => 'Incremented version; Added blog as a special album; Inserts menu item for mobile',
    'views/scripts/photo/view.tpl' => 'Added rotate and flip options',
  ),
  '4.1.3' => array(
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/photo/view.tpl' => 'Can now use left and right arrow keys for prev/next photo',
  ),
  '4.1.2' => array(
    '/application/languages/en/album.csv' => 'Added phrases',
    'controllers/AlbumController.php' => 'Added ability to order photos in an album',
    'controllers/PhotoController.php' => 'Added ability to edit title/description of photo through the view page',
    'externals/styles/main.css' => 'Added styles',
    'Form/Album/EditPhoto.php' => 'Added',
    'Form/Photo/Delete.php' => 'Added',
    'Form/Photo/Edit.php' => 'Refactored',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added new widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.1-4.1.2.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/album/editphotos.tpl' => 'Fixed missing closing tag',
    'views/scripts/album/view.tpl' => 'Added ability to order photos in an album',
    'views/scripts/photo/delete.tpl' => 'Added',
    'views/scripts/photo/edit.tpl' => 'Added',
    'views/scripts/photo/view.tpl' => 'Use AJAX friend list retrieval by default on photo tagging',
    'widgets/list-popular-albums/Controller.php' => 'Added',
    'widgets/list-popular-albums/index.tpl' => 'Added',
    'widgets/list-popular-photos/Controller.php' => 'Added',
    'widgets/list-popular-photos/index.tpl' => 'Added',
    'widgets/list-recent-albums/Controller.php' => 'Added',
    'widgets/list-recent-albums/index.tpl' => 'Added',
    'widgets/list-recent-photos/Controller.php' => 'Added',
    'widgets/list-recent-photos/index.tpl' => 'Added',
  ),
  '4.1.1' => array(
    'Api/Core.php' => 'Changes for storage system modifications; fixed incorrect storage system params (in Model/Photo.php)',
    'controllers/AdminSettingsController.php' => 'Newly created categories gets the correct owner id',
    'controllers/AlbumController.php' => 'Moved photo handling into a setPhoto() method',
    'controllers/IndexController.php' => 'Moved photo handling into a setPhoto() method',
    'externals/.htaccess' => 'Added keywords; removed deprecated code',
    'Model/Album.php' => 'Changes for storage system modifications',
    'Model/Photo.php' => 'Changes for storage system modifications; moved photo handling into a setPhoto() method',
    'Plugin/Core.php' => 'Changes for storage system modifications; moved photo handling into a setPhoto() method',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.0-4.1.1.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-settings/categories.tpl' => 'Hides the owner id column when viewing categories',
  ),
  '4.1.0' => array(
    '/application/languages/en/album.csv' => 'Added phrases',
    'controllers/AdminLevelController.php' => 'Added notice on form save',
    'controllers/AdminManageController.php' => 'Fixed issue with album deletion',
    'controllers/AdminSettingsController.php' => 'Added notice on form save',
    'controllers/AlbumController.php' => 'Fixed UI issue with smoothboxes',
    'controllers/IndexController.php' => 'Improved search function on manage page',
    'externals/styles/main.css' => 'Fixed minor style issues',
    'Form/Album.php' => 'Fixed issue with disabled privacy options',
    'Form/Album/Edit.php' => 'Fixed issue with disabled privacy options',
    'Model/Photo.php' => 'Fixed issue with deleting profile photos when the album plugin is not installed',
    'Plugin/Job/Maintenance/RebuildPrivacy.php' => 'Added',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Removed',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added pagination/item count limits to widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Backwards compatibility fix for tasks modifications',
    'settings/my-upgrade-4.0.5-4.1.0.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/delete.tpl' => 'Added',
    'views/scripts/admin-manage/index.tpl' => 'Adjusted return link',
    'views/scripts/index/browse.tpl' => 'Fixed UTF-8 truncation issue',
    'views/scripts/index/manage.tpl' => 'Added filter form',
    'views/scripts/index/upload.tpl' => 'Hides irrelevant form values when adding photos to existing album',
    'views/scripts/photo/view.tpl' => 'Added comment for AJAX friend retrieval',
    'widgets/profile-albums/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-albums/index.tpl' => 'Added pagination/item count limit',
  ),
  '4.0.5' => array(
    'controllers/AdminLevelController.php' => 'Fixed bug preventing switching level',
    'controllers/AlbumController.php' => 'Added registered privacy type',
    'Form/Admin/Settings/Level.php' => 'Added registered privacy type',
    'Form/Album.php' => 'Added registered privacy type',
    'Form/Album/Edit.php' => 'Added registered privacy type',
    'Model/Album.php' => 'Removed redundant search columns',
    'Model/Photo.php' => 'Removed redundant search columns',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added idle support; added registered privacy type',
    'settings/changelog.php' => 'Added',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-level/index.tpl' => 'Fixed bug preventing switching level',
    'views/scripts/album/view.tpl' => 'Fixes rare error with empty titles',
  ),
  '4.0.4' => array(
    'controllers/AlbumController.php' => 'Tweak for message photos',
    'externals/styles/main.css' => 'Improved RTL support',
    'Model/DbTable/Albums.php' => 'Tweak for message photos',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added to fix privacy issues in the feed',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/_composePhoto.tpl' => 'Added missing translation',
    'views/scripts/_formButtonCancel.tpl' => 'Removing deprecated code',
    'views/scripts/photo/view.tpl' => 'Added missing translation',
  ),
  '4.0.3' => array(
    'controllers/IndexController.php' => 'Quick navigation uses menu system',
    'Plugin/Menus.php' => 'Better auth handling for menus',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.2-4.0.3.sql' => 'Added',
    'settings/my.sql' => 'Added album menus to the menu editor; quick navigation uses menu system; incremented version',
    'views/scripts/admin-manage/index.tpl' => 'Correct locale date formatting; added missing translation',
    'views/scripts/admin-settings/categories.tpl' => 'Added missing translation',
    'views/scripts/admin-settings/index.tpl' => 'Added missing translation',
    'views/scripts/index/browse.tpl' => 'Quick navigation uses menu system',
    'views/scripts/index/manage.tpl' => 'Quick navigation uses menu system',
    '/application/languages/en/album.csv' => 'Added phrases',
  ),
  '4.0.2' => array(
    'Api/Core.php' => 'Categories ordered by name',
    'controllers/AdminLevelController.php' => 'Various level settings fixes and enhancements',
    'controllers/AlbumController.php' => 'Fixed activity privacy rebinding problem',
    'controllers/IndexController.php' => 'Fixed problem setting the category in browse',
    'Form/Admin/Level.php' => 'Moved',
    'Form/Admin/Settings/Level.php' => 'Various level settings fixes and enhancements',
    'Model/Photo.php' => 'Added missing parent::_postDelete(), could have caused issues with orphaned rows',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Added',
    'settings/my.sql' => 'Various level settings fixes and enhancements',
    '/application/languages/en/album.csv' => 'Fix activity feed translations',
  ),
  '4.0.1' => array(
    'Api/Core.php' => 'Cleanup of temporary files; adjustment for trial',
    'controllers/AlbumController.php' => 'Fixed missing level permissions check',
    'controllers/PhotoController.php' => 'Fixed missing level permissions check; added view count support',
    'Form/Admin/Level.php' => 'Source code formatting',
    'Plugin/Core.php' => 'Query optimization',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.0-4.0.1.sql' => 'Added',
    'settings/my.sql' => 'Added missing view_count and comment_count columns to the engine4_album_photos table',
  ),
) ?>